name    'puppetlabs-horizon'
version '3.0.0'
source  'https://github.com/stackforge/puppet-horizon'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Horizon Module'
description  'Puppet module to install and configure the OpenStack Horizone dashboard'
project_page 'https://launchpad.net/puppet-openstack'

dependency 'saz/memcached', '>= 2.0.2 <3.0.0'
dependency 'puppetlabs/apache', '>= 0.4.0 <1.0.0'
dependency 'puppetlabs/stdlib', '>= 2.5.0'
