name         'puppetlabs-horizon'
version      '4.0.0'
author       'Puppet Labs and StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Horizon'
description  'Installs and configures OpenStack Horizon (Dashboard).'
project_page 'https://launchpad.net/puppet-horizon'
source       'https://github.com/stackforge/puppet-horizon'

dependency 'puppetlabs/apache', '>= 1.0.0 <2.0.0'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'saz/memcached', '>= 2.0.2 <3.0.0'
