name    'puppetlabs-horizon'
version '1.0.0'
source 'https://github.com/puppetlabs/puppetlabs-horizon'
author 'Puppet Labs'
license 'Apache License 2.0'
summary 'Horizon Dashboard Folsom Module for Puppet'
project_page 'https://github.com/puppetlabs/puppetlabs-horizon'

dependency 'saz/memcached', '>= 2.0.2'
dependency 'puppetlabs/apache', '>= 0.4.0'
dependency 'puppetlabs/stdlib', '>= 2.4.0'
dependency 'puppetlabs/apache', '>= 0.4.0'
